# Generated by Django 5.1.5 on 2025-01-28 18:41

import logging
import os
from django.db import migrations

logger = logging.getLogger(__name__)

def generate_superuser(apps, schema_editor):
    from django.contrib.auth import get_user_model

    USERNAME = os.environ.get("ADMIN_USERNAME")
    PASSWORD = os.environ.get("ADMIN_PASSWORD")
    EMAIL = os.environ.get("ADMIN_EMAIL")

    user = get_user_model()

    if not user.objects.filter(username=USERNAME, email=EMAIL).exists():
        logger.info("Creating new superuser")
        admin = user.objects.create_superuser(
           username=USERNAME, password=PASSWORD, email=EMAIL
        )
        admin.save()
    else:
        logger.info("Superuser already created!")


class Migration(migrations.Migration):
   dependencies = []

   operations = [migrations.RunPython(generate_superuser)]
