# Generated by Django 5.1.5 on 2025-01-28 18:41

import logging
import os
from django.db import migrations

logger = logging.getLogger(__name__)

def generate_superuser(apps, schema_editor):

    USERNAME = os.environ.get("ADMIN_USERNAME", "admin")
    PASSWORD = os.environ.get("ADMIN_PASSWORD", "admin")
    EMAIL = os.environ.get("ADMIN_EMAIL", "admin@localhost")

    User = apps.get_model('auth', 'User')

    logger.info("Creating new superuser")
    admin = User.objects.create_superuser(
        username=USERNAME, password=PASSWORD, email=EMAIL
    )
    admin.save()


class Migration(migrations.Migration):
   dependencies = []

   operations = [migrations.RunPython(generate_superuser)]
